app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 604800000

  cors:
    allowedOrigins : "*"
application:
  description: HLF  REST API Middleware for dgital contract chain.
  version: 1.0.0
springdoc:
  api-docs.enabled: true
 
  swagger-ui:
    url: http://localhost:8080
    operationsSorter: alpha
    path: /swagger-ui.html
    tagsSorter: alpha
    properties:
      title: Spring Pageable response
      description: demo project for returning pageable object containing data for easy filtering and pageing in the UI
spring:
   profiles.active: local